spring:
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.example.ecommerce: INFO

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    enabled: false  # Disable Swagger in production
